server:
  port: 10130
  servlet:
    context-path: /coin
  undertow:
    io-threads: 32
    worker-threads: 256

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown, health
      base-path: /
